steps:
# Build
- name: 'gcr.io/cloud-builders/docker'
  id: 'base'
  args:
  - 'build'
  - '--tag=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
  - '.'
  waitFor: ['-']

# Push
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-base'
  args:
  - 'push'
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
  waitFor: ['base']

# Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image'
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--no-allow-unauthenticated'
  waitFor: ['push-base']

images:
- 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
